#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: meson
# autospec version: v27
# autospec commit: 65cf152
#
Name     : yelp-xsl
Version  : 42.4
Release  : 30
URL      : https://download.gnome.org/sources/yelp-xsl/42/yelp-xsl-42.4.tar.xz
Source0  : https://download.gnome.org/sources/yelp-xsl/42/yelp-xsl-42.4.tar.xz
Summary  : Yelp XSLT Stylesheets
Group    : Development/Tools
License  : GPL-2.0 LGPL-2.1 MIT
Requires: yelp-xsl-data = %{version}-%{release}
Requires: yelp-xsl-license = %{version}-%{release}
BuildRequires : buildreq-gnome
BuildRequires : buildreq-meson
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
These are the CSS text template files used by these XSLT stylesheets.
They are maintained in separate files to make it easier to work on them.
You can call variables or XPath expression with double curly braces {{$like_this}}.
Variables are defined in the XSLT files.

%package data
Summary: data components for the yelp-xsl package.
Group: Data

%description data
data components for the yelp-xsl package.


%package dev
Summary: dev components for the yelp-xsl package.
Group: Development
Requires: yelp-xsl-data = %{version}-%{release}
Provides: yelp-xsl-devel = %{version}-%{release}
Requires: yelp-xsl = %{version}-%{release}

%description dev
dev components for the yelp-xsl package.


%package license
Summary: license components for the yelp-xsl package.
Group: Default

%description license
license components for the yelp-xsl package.


%prep
%setup -q -n yelp-xsl-42.4
cd %{_builddir}/yelp-xsl-42.4
pushd ..
cp -a yelp-xsl-42.4 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1750261741
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
meson --libdir=lib64 --prefix=/usr --buildtype=plain   builddir
ninja -v -C builddir
GOAMD64=v3
CFLAGS="$CFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 " CXXFLAGS="$CXXFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 " LDFLAGS="$LDFLAGS -march=x86-64-v3 " meson --libdir=lib64 --prefix=/usr --buildtype=plain   builddiravx2
ninja -v -C builddiravx2

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
mkdir -p %{buildroot}/usr/share/package-licenses/yelp-xsl
cp %{_builddir}/yelp-xsl-%{version}/COPYING.GPL %{buildroot}/usr/share/package-licenses/yelp-xsl/b47456e2c1f38c40346ff00db976a2badf36b5e3 || :
cp %{_builddir}/yelp-xsl-%{version}/COPYING.LGPL %{buildroot}/usr/share/package-licenses/yelp-xsl/545f380fb332eb41236596500913ff8d582e3ead || :
cp %{_builddir}/yelp-xsl-%{version}/COPYING.MIT %{buildroot}/usr/share/package-licenses/yelp-xsl/d2f2f629751ab559d8b25418bbfc2b1dedf66618 || :
GOAMD64=v3
DESTDIR=%{buildroot}-v3 ninja -C builddiravx2 install
GOAMD64=v2
DESTDIR=%{buildroot} ninja -C builddir install
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/yelp-xsl/js/highlight.pack.js
/usr/share/yelp-xsl/xslt/common/color.xsl
/usr/share/yelp-xsl/xslt/common/css/core.css.tmpl
/usr/share/yelp-xsl/xslt/common/css/docbook.css.tmpl
/usr/share/yelp-xsl/xslt/common/css/elements.css.tmpl
/usr/share/yelp-xsl/xslt/common/css/mallard-editor.css.tmpl
/usr/share/yelp-xsl/xslt/common/css/mallard.css.tmpl
/usr/share/yelp-xsl/xslt/common/css/syntax.css.tmpl
/usr/share/yelp-xsl/xslt/common/domains/yelp-xsl.xml
/usr/share/yelp-xsl/xslt/common/html.xsl
/usr/share/yelp-xsl/xslt/common/icons.xsl
/usr/share/yelp-xsl/xslt/common/icons/yelp-note-advanced.svg
/usr/share/yelp-xsl/xslt/common/icons/yelp-note-bug.svg
/usr/share/yelp-xsl/xslt/common/icons/yelp-note-important.svg
/usr/share/yelp-xsl/xslt/common/icons/yelp-note-note.svg
/usr/share/yelp-xsl/xslt/common/icons/yelp-note-package.svg
/usr/share/yelp-xsl/xslt/common/icons/yelp-note-tip.svg
/usr/share/yelp-xsl/xslt/common/icons/yelp-note-warning.svg
/usr/share/yelp-xsl/xslt/common/l10n-numbers.xsl
/usr/share/yelp-xsl/xslt/common/l10n.xsl
/usr/share/yelp-xsl/xslt/common/tmpl.xsl
/usr/share/yelp-xsl/xslt/common/ttml.xsl
/usr/share/yelp-xsl/xslt/common/utils.xsl
/usr/share/yelp-xsl/xslt/docbook/common/db-chunk.xsl
/usr/share/yelp-xsl/xslt/docbook/common/db-common.xsl
/usr/share/yelp-xsl/xslt/docbook/common/db-profile.xsl
/usr/share/yelp-xsl/xslt/docbook/common/db-selectors.mod
/usr/share/yelp-xsl/xslt/docbook/common/db-title.xsl
/usr/share/yelp-xsl/xslt/docbook/common/db-xref.xsl
/usr/share/yelp-xsl/xslt/docbook/html/db2html-bibliography.xsl
/usr/share/yelp-xsl/xslt/docbook/html/db2html-block.xsl
/usr/share/yelp-xsl/xslt/docbook/html/db2html-callout.xsl
/usr/share/yelp-xsl/xslt/docbook/html/db2html-classsynopsis.xsl
/usr/share/yelp-xsl/xslt/docbook/html/db2html-cmdsynopsis.xsl
/usr/share/yelp-xsl/xslt/docbook/html/db2html-division.xsl
/usr/share/yelp-xsl/xslt/docbook/html/db2html-ebnf.xsl
/usr/share/yelp-xsl/xslt/docbook/html/db2html-footnote.xsl
/usr/share/yelp-xsl/xslt/docbook/html/db2html-funcsynopsis.xsl
/usr/share/yelp-xsl/xslt/docbook/html/db2html-index.xsl
/usr/share/yelp-xsl/xslt/docbook/html/db2html-inline.xsl
/usr/share/yelp-xsl/xslt/docbook/html/db2html-links.xsl
/usr/share/yelp-xsl/xslt/docbook/html/db2html-list.xsl
/usr/share/yelp-xsl/xslt/docbook/html/db2html-math.xsl
/usr/share/yelp-xsl/xslt/docbook/html/db2html-media.xsl
/usr/share/yelp-xsl/xslt/docbook/html/db2html-refentry.xsl
/usr/share/yelp-xsl/xslt/docbook/html/db2html-suppressed.xsl
/usr/share/yelp-xsl/xslt/docbook/html/db2html-table.xsl
/usr/share/yelp-xsl/xslt/docbook/html/db2html-xref.xsl
/usr/share/yelp-xsl/xslt/docbook/html/db2html.xsl
/usr/share/yelp-xsl/xslt/docbook/html/db2xhtml.xsl
/usr/share/yelp-xsl/xslt/mallard/cache/mal-cache.xsl
/usr/share/yelp-xsl/xslt/mallard/common/mal-gloss.xsl
/usr/share/yelp-xsl/xslt/mallard/common/mal-if.xsl
/usr/share/yelp-xsl/xslt/mallard/common/mal-link.xsl
/usr/share/yelp-xsl/xslt/mallard/common/mal-sort.xsl
/usr/share/yelp-xsl/xslt/mallard/html/mal2html-api.xsl
/usr/share/yelp-xsl/xslt/mallard/html/mal2html-block.xsl
/usr/share/yelp-xsl/xslt/mallard/html/mal2html-gloss.xsl
/usr/share/yelp-xsl/xslt/mallard/html/mal2html-inline.xsl
/usr/share/yelp-xsl/xslt/mallard/html/mal2html-links.xsl
/usr/share/yelp-xsl/xslt/mallard/html/mal2html-list.xsl
/usr/share/yelp-xsl/xslt/mallard/html/mal2html-math.xsl
/usr/share/yelp-xsl/xslt/mallard/html/mal2html-media.xsl
/usr/share/yelp-xsl/xslt/mallard/html/mal2html-page.xsl
/usr/share/yelp-xsl/xslt/mallard/html/mal2html-svg.xsl
/usr/share/yelp-xsl/xslt/mallard/html/mal2html-table.xsl
/usr/share/yelp-xsl/xslt/mallard/html/mal2html-ui.xsl
/usr/share/yelp-xsl/xslt/mallard/html/mal2html.xsl
/usr/share/yelp-xsl/xslt/mallard/html/mal2xhtml.xsl

%files dev
%defattr(-,root,root,-)
/usr/share/pkgconfig/yelp-xsl.pc

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/yelp-xsl/545f380fb332eb41236596500913ff8d582e3ead
/usr/share/package-licenses/yelp-xsl/b47456e2c1f38c40346ff00db976a2badf36b5e3
/usr/share/package-licenses/yelp-xsl/d2f2f629751ab559d8b25418bbfc2b1dedf66618
